'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8'),LampyPatchAddress=require('../js/patch-address-review.js');
function source(name){const start=html.search(new RegExp('function '+name+'\\('));assert(start>=0,name);for(let end=html.indexOf('}',start);end>=0;end=html.indexOf('}',end+1)){const code=html.slice(start,end+1);try{new Function('return ('+code+')');return code}catch{}}throw Error(name)}
function load(c,...names){names.forEach(name=>vm.runInContext(source(name),c))}
const plain=value=>JSON.parse(JSON.stringify(value)),escapeHtml=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const rows=[{id:'a',fixId:'101',fixture:'Spot',channels:10,universe:'1',address:'1',location:'Front'},{id:'b',fixId:'102',fixture:'Wash',channels:8,universe:'1',address:'20',location:'Rear'},{id:'c',fixId:'103',fixture:'Wash',channels:12,universe:'1',address:'100',location:''},{id:'d',fixId:'104',fixture:'Spot',channels:10,universe:'2',address:'1'}];
const c=vm.createContext({console,app:{fixturePatch:plain(rows),patchSheets:[{id:'comparison',rows:plain(rows)}]},universeSelectedIds:new Set(),universeSelectionAnchor:'',universeSelectionProject:null,activeUniverseDetail:'1',activeSheetTab:'fixturePatch',universeDragCancel:null,patchAddressReview:null,LampyPatchAddress,escapeHtml,escapeAttr:escapeHtml,escapeJsAttr:escapeHtml,refreshUniverseSelection:()=>{},render:()=>{},alert:message=>c.alerts.push(message),alerts:[],clonePatchState:plain,recordFixturePatchUndo:label=>{c.undoCount++;c.fixturePatchUndoHistory.unshift({label})},fixturePatchUndoHistory:[],undoCount:0,confirmedDuplicateAddressKeys:new Set(),persist:()=>c.saves++,saves:0,refreshHomeIfActive:()=>{},closePatchGroupEditModal:()=>{}});
c.patchFixtureRows=()=>c.app.fixturePatch;
const elements=new Map();c.$=id=>{if(!elements.has(id))elements.set(id,{classList:{add(){},remove(){}},focus(){},textContent:''});return elements.get(id)};
load(c,'universeRows','universeMoveProposals','universeDragProposal','syncUniverseSelection','selectUniverseFixture','selectAllUniverseFixtures','reviewUniverseMove','moveSelectedUniverse','moveActiveUniverse','patchAddressSnapshot','openPatchAddressReview','confirmPatchAddressReview','closePatchAddressReview','setUniverseDetailTab','patchToolbarMenuMarkup','fixturePatchSubTabsMarkup','universeViewerCellMarkup','universeDetailsMarkup');
c.renderPatchAddressReview=()=>{};
// Selection is scoped to the current Master Patch universe and reset on project changes.
c.syncUniverseSelection();c.selectUniverseFixture('a');c.selectUniverseFixture('c',{shiftKey:true});assert.deepEqual([...c.universeSelectedIds],['a','b','c']);c.selectUniverseFixture('b');assert(!c.universeSelectedIds.has('b'));c.selectAllUniverseFixtures(true);assert.equal(c.universeSelectedIds.size,3);c.selectAllUniverseFixtures(false);assert.equal(c.universeSelectedIds.size,0);
c.selectUniverseFixture('a');c.setUniverseDetailTab('2');assert.equal(c.universeSelectedIds.size,0);c.activeUniverseDetail='1';c.app={...c.app};c.syncUniverseSelection();assert.equal(c.universeSelectionAnchor,'');
// Movement preserves explicit addresses and changes no project records before confirmation.
const before=JSON.stringify(c.app);const proposals=c.universeMoveProposals(rows.slice(0,2),'3');assert.deepEqual(plain(proposals.map(row=>[row.id,row.address,row.universe])),[['a','1','3'],['b','20','3']]);assert.equal(JSON.stringify(c.app),before);
for(const target of ['',0,-1,'2x','2.1','9007199254740993'])assert.throws(()=>c.universeMoveProposals(rows,target));
c.reviewUniverseMove([c.app.fixturePatch[0]],'3');assert.equal(c.patchAddressReview.proposals.length,1);assert.equal(c.saves,0);assert.equal(JSON.stringify(c.app),before);c.closePatchAddressReview();assert.equal(JSON.stringify(c.app),before);
c.reviewUniverseMove(c.app.fixturePatch.slice(0,2),'3');c.confirmPatchAddressReview();assert.equal(c.saves,1);assert.equal(c.undoCount,1);assert.equal(c.activeUniverseDetail,'3');assert.equal(c.app.fixturePatch[2].universe,'1');assert.equal(c.app.patchSheets[0].rows[0].universe,'1','comparison never mutated');c.confirmPatchAddressReview();assert.equal(c.saves,1);
// Stale proposals reject; collisions clear only proposed addresses upon explicit confirmation.
c.reviewUniverseMove([c.app.fixturePatch[0]],'4');c.app.fixturePatch[2].location='Changed';c.confirmPatchAddressReview();assert.equal(c.saves,1);assert(c.alerts.at(-1).includes('patch changed'));
c.reviewUniverseMove([c.app.fixturePatch[0]],'2');c.confirmPatchAddressReview();assert.equal(c.app.fixturePatch[0].address,'');assert.equal(c.app.fixturePatch[0].universe,'2');assert.equal(c.app.fixturePatch[0].channels,10);assert.equal(c.app.fixturePatch[3].address,'1');assert.equal(c.saves,2);
const overlap=[{...rows[0],universe:'4'},{...rows[1],universe:'4',address:'5'}];assert(LampyPatchAddress.validate(rows,overlap).every(result=>result.state==='invalid'));
assert.equal(c.universeDragProposal(rows[1],23,45).address,'42','preserves grabbed offset across grid row');assert.equal(c.universeDragProposal(rows[1],23,2).address,'-1');assert.equal(LampyPatchAddress.validate(rows,[c.universeDragProposal(rows[1],20,510)])[0].state,'invalid');assert.equal(LampyPatchAddress.validate(rows,[c.universeDragProposal(rows[1],20,21)])[0].state,'valid','old footprint excluded');
// Menus, navigation and range identity/tooltip content.
assert(!c.patchToolbarMenuMarkup(false).includes('<details'));assert(c.patchToolbarMenuMarkup(false).includes('Import'));for(const name of ['Import','Export','Fixture Summary','Position Summary'])assert(c.patchToolbarMenuMarkup(true).includes('>'+name+'</button>'));
assert(c.fixturePatchSubTabsMarkup().includes('Universe Detail'));assert(source('updateSheetTabs').includes("activeSheetTab==='universeDetail'?'fixturePatch'"));assert(source('navigateHomeStat').includes('openUniverseDetailPage'));assert(source('renderFixturePatchView').includes('patchToolbarMenuMarkup(rows.length>0)'));
const map=new Map(Array.from({length:10},(_,i)=>[i+1,rows[0]])),cell=c.universeViewerCellMarkup(1,map,'1');assert(cell.includes('>#101</span>'));assert(cell.includes('#101 · Spot · Front'));assert(cell.includes('tabindex="0"'));assert(cell.includes('data-universe-fixture="a"'));
// Exercise production pointer handlers with DOM coordinates (no browser).
class Cell{constructor(address,id){this.dataset={universeAddress:String(address),...(id?{universeFixture:id}:{})};this.classes=new Set();this.classList={add:v=>this.classes.add(v),remove:(...v)=>v.forEach(x=>this.classes.delete(x))};this.title='Fixture';}closest(query){return query==='[data-universe-fixture]'&&!this.dataset.universeFixture?null:this}}
const cells=Array.from({length:512},(_,i)=>new Cell(i+1,i<10?'a':i>=19&&i<27?'b':null));let point=null,capture=false;
const listeners=new Map(),docListeners=new Map(),grid={addEventListener:(type,fn)=>listeners.set(type,fn),removeEventListener:(type,fn)=>{if(listeners.get(type)===fn)listeners.delete(type)},contains:cell=>cells.includes(cell),setPointerCapture:()=>capture=true,hasPointerCapture:()=>capture,releasePointerCapture:()=>capture=false,querySelectorAll:query=>query==='[data-universe-address]'?cells:cells.filter(cell=>cell.classes.has('universeDropValid')||cell.classes.has('universeDropInvalid'))};
let reviews=[],selected=[];
const drag=vm.createContext({console,app:{fixturePatch:plain(rows)},patchFixtureRows:()=>drag.app.fixturePatch,patchAddressSnapshot:()=>JSON.stringify(drag.app.fixturePatch),patchAddressReview:null,universeDragCancel:null,LampyPatchAddress,document:{elementFromPoint:()=>point,addEventListener:(type,fn)=>docListeners.set(type,fn),removeEventListener:(type,fn)=>{if(docListeners.get(type)===fn)docListeners.delete(type)}} ,$:()=>elements.get('universeDragStatus'),openPatchAddressReview:proposal=>reviews.push(plain(proposal)),selectUniverseFixture:id=>selected.push(id),alert:message=>drag.alerts.push(message),alerts:[]});
elements.set('universeDragStatus',{textContent:''});load(drag,'universeDragProposal','attachUniverseGridEvents');drag.attachUniverseGridEvents({querySelector:()=>grid});
const e=(cell,x=0,y=0)=>({target:cell,button:0,pointerId:1,clientX:x,clientY:y,preventDefault(){},stopPropagation(){}}),start=(address=23)=>listeners.get('pointerdown')(e(cells[address-1])),move=(address)=>{point=address?cells[address-1]:null;listeners.get('pointermove')(e(point,30,30))},up=()=>listeners.get('pointerup')(e(point,30,30));
start();move(45);assert(cells[41].classes.has('universeDropValid'));assert(elements.get('universeDragStatus').textContent.includes('42–49'));up();assert.equal(reviews.at(-1)[0].address,'42');assert(!capture);assert.equal(drag.app.fixturePatch[1].address,'20');
start();move(4);assert(cells[0].classes.has('universeDropInvalid'));up();assert.equal(reviews.at(-1)[0].address,'1','invalid destination still goes to review');
start();move(512);assert(cells[508].classes.has('universeDropInvalid'));assert(elements.get('universeDragStatus').textContent.includes('beyond 512'));const count=reviews.length;docListeners.get('keydown')({...e(null),key:'Escape'});assert.equal(reviews.length,count);assert(!listeners.has('pointerup'));assert(!capture);
start();move(45);listeners.get('pointercancel')(e(null));assert.equal(reviews.length,count);start();move(null);up();assert.equal(reviews.length,count);
start();move(45);drag.app.fixturePatch[2].address='120';up();assert.equal(reviews.length,count);assert(drag.alerts.at(-1).includes('patch changed'));
start();point=cells[22];listeners.get('pointerup')(e(point));assert.equal(selected.at(-1),'b','click selects without a review');
assert(source('attachUniverseGridEvents').includes('document.elementFromPoint(e.clientX,e.clientY)'));assert(!source('attachUniverseGridEvents').includes('offsetX'),'hit testing must not assume unscaled geometry');
// PDF session isolation, populated/empty buttons and group-specific omission.
const host={innerHTML:''},pdfRows=[{fixId:'1',universe:'1',address:'1',mode:'Full',notes:''},{fixId:'2',universe:'1',address:'11',mode:'',notes:''}],pdf=vm.createContext({console,patchColumnsContext:'pdf',patchPdfColumnSelection:{fixId:true,mode:true,notes:true,universeAddress:true},fixturePatchViewOptions:{columns:{fixId:true,mode:false,notes:true},universeAddress:{enabled:true,separator:'.',visible:true}},PATCH_COLUMNS:[{key:'fixId',field:'fixId',label:'Fix ID'},{key:'universe',field:'universe',label:'Universe'},{key:'address',field:'address',label:'Address'},{key:'mode',field:'mode',label:'Mode'},{key:'notes',field:'notes',label:'Notes'}],escapeHtml,escapeAttr:escapeHtml,escapeJsAttr:escapeHtml,patchPdfExportRows:()=>pdfRows,$:()=>host,renderFixturePatchPdfPreview:()=>pdf.renders++,renders:0,alert:()=>{},persist:()=>{throw Error('PDF choices must not persist')},refreshPatchColumnViews:()=>{throw Error('PDF choices must not affect live tables')}});
load(pdf,'patchColumnDefinitions','patchColumnVisible','patchVisibleColumns','patchUniverseAddressText','patchColumnValue','patchPdfExportColumns','patchPdfHiddenColumns','renderPatchColumnsModal','togglePatchColumn','showAllPatchColumns');
const saved=JSON.stringify(pdf.fixturePatchViewOptions);pdf.renderPatchColumnsModal();assert(host.innerHTML.includes('aria-pressed="true"'));assert(host.innerHTML.includes('disabled title="Empty throughout the exported selection"'));assert(!host.innerHTML.includes('type="checkbox"'));assert(host.innerHTML.includes('Universe / Address'));
pdf.togglePatchColumn('mode',false);assert.equal(pdf.renders,1);assert(!pdf.patchPdfExportColumns().some(col=>col.key==='mode'));assert.equal(JSON.stringify(pdf.fixturePatchViewOptions),saved);
pdf.showAllPatchColumns();assert(pdf.patchPdfExportColumns().some(col=>col.key==='mode'));assert(!pdf.patchPdfExportColumns([pdfRows[1]]).some(col=>col.key==='mode'));assert(!pdf.patchPdfExportColumns().some(col=>col.key==='notes'));assert.equal(JSON.stringify(pdf.fixturePatchViewOptions),saved);
pdf.patchPdfColumnSelection=null;assert(!pdf.patchPdfExportColumns().some(col=>col.key==='mode'),'without a session live preferences apply');assert(source('openFixturePatchPdfPreview').includes('patchPdfColumnSelection=Object.fromEntries'));assert(source('closeFixturePatchPdfPreview').includes('patchPdfColumnSelection=null'));
const modal=html.slice(html.indexOf('<div id="fixturePatchPdfModal"'),html.indexOf('<div id="fixturePatchPdfModal"')+8500),optionsEnd=modal.indexOf('</details>');assert(modal.indexOf('id="patchPdfShowSummary"')>optionsEnd);assert(modal.indexOf('data-patch-pdf-hidden-columns')<modal.indexOf('id="patchPdfShowSummary"'));assert(modal.indexOf('id="patchPdfShowRevisionNotes"')<modal.indexOf('data-pdf-logo-preview-controls'));assert(html.includes('<th aria-label="Quantity" title="Quantity">Qty</th>'));
console.log('PASS: V51 universe selection, reviewed moves/drags, cancellation, stale proposals, menu/navigation and isolated PDF columns.');
// The PDF framework reorganises controls on every open; exercise that path as well as raw markup.
class Node{
 constructor(cls='',attrs=[]){this.className=cls;this.attrs=new Set(attrs);this.children=[];this.parent=null;this.classList={add:()=>{}}}
 appendChild(node){if(node.parent)node.parent.children=node.parent.children.filter(child=>child!==node);this.children.push(node);node.parent=this;return node}
 insertBefore(node,before){this.appendChild(node);if(before){this.children.pop();this.children.splice(this.children.indexOf(before),0,node)}}
 replaceChildren(...nodes){this.children.forEach(node=>node.parent=null);this.children=[];nodes.forEach(node=>this.appendChild(node))}
 hasAttribute(attr){return this.attrs.has(attr)}
 closest(){return null}
 querySelector(){return null}
 querySelectorAll(query){return this.children.flatMap(node=>[...(query==='.ctl'&&node.className==='ctl'?[node]:[]),...node.querySelectorAll(query)])}
}
const controls=new Node(),hidden=new Node('ctl',['data-patch-pdf-hidden-columns']),pages=new Node('ctl',['data-patch-pdf-page-options']),logos=new Node('ctl',['data-pdf-logo-preview-controls']);[hidden,pages,logos].forEach(node=>controls.appendChild(node));
const organising=vm.createContext({ensurePdfPreviewWorkspace:()=>({modal:{querySelector:()=>null,querySelectorAll:()=>[]},side:{},controls}),pdfPreviewSideSection:(title,cls)=>{const node=new Node(cls);node.appendChild(new Node('heading'));return node},$:()=>null});load(organising,'organisePdfPreviewSidePane');
for(let i=0;i<2;i++){organising.organisePdfPreviewSidePane('patch','fixturePatchPdfModal');assert.deepEqual(controls.children.map(node=>node.className),['pdfPreviewSheetOptions','patchPdfPageOptions','pdfPreviewLogoOptions']);assert.equal(pages.parent.className,'patchPdfPageOptions');assert.equal(hidden.parent.className,'pdfPreviewSheetOptions')}
// Selection rendering must include every occupied channel, and never paint an unaddressed fixture.
const drawRows=[{id:'a',address:'3',channels:4},{id:'blank',address:'',channels:10}],drawCells=Array.from({length:12},(_,index)=>({dataset:{universeAddress:String(index+1)},classList:{toggle:(_,value)=>drawCells[index].selected=value}}));
const drawing=vm.createContext({activeUniverseDetail:'1',universeSelectedIds:new Set(['a','blank']),universeRows:()=>drawRows,document:{querySelectorAll:selector=>selector==='[data-universe-address]'?drawCells:[]}});load(drawing,'refreshUniverseSelection');drawing.refreshUniverseSelection();assert.deepEqual(drawCells.map((cell,index)=>cell.selected?index+1:0).filter(Boolean),[3,4,5,6]);
console.log('PASS: V51 repeated PDF-side-pane organisation and exact selected channel bounds.');
